{
 "title": "URL Shortener Metrics",
 "tags": [
  "prometheus",
  "url-shortener"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Total URLs Created",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 6 },
   "targets": [
    { "expr": "urls_total" }
   ]
  },
  {
   "title": "URLs Currently in DB",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 6 },
   "targets": [
    { "expr": "urls_in_db" }
   ]
  },
  {
   "title": "URLs Created Over Time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    { "expr": "increase(urls_total[1m])" }
   ]
  },
  {
   "title": "URLs Count in DB Over Time",
   "type": "graph",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
   "targets": [
    { "expr": "urls_in_db" }
   ]
  }
 ]
}