package main

import (
	"fmt"
	_ "github.com/zen-flo/url-shortener/docs" // docs are generated by Swag CLI
	"github.com/zen-flo/url-shortener/internal/db"
	"github.com/zen-flo/url-shortener/internal/handler"
	"github.com/zen-flo/url-shortener/internal/service"
	"net/http"
	"time"
)

/*
Main function starts the HTTP server for the URL Shortener API.
*/

// @title URL Shortener API
// @version 1.0
// @description Simple REST API for shortening URLs.
// @host localhost:8080
// @BasePath /
func main() {
	// Initialize database
	database := db.InitDB("urls.db")
	defer func() {
		if err := database.Close(); err != nil {
			fmt.Printf("Error closing database: %v\n", err)
		}
	}()

	// Initialize service and handler
	urlService := service.NewURLService(database)
	urlHandler := handler.NewURLHandler(urlService)

	// Create router
	r := NewRouter(urlHandler)

	// Start background metrics updater
	go func() {
		ticker := time.NewTicker(time.Minute)
		defer ticker.Stop()
		for range ticker.C {
			urlService.UpdateURLCount()
		}
	}()

	// Server port
	port := 8080
	fmt.Printf("Starting server on port %d...\n", port)

	// Start HTTP server
	if err := http.ListenAndServe(fmt.Sprintf(":%d", port), r); err != nil {
		fmt.Printf("Error starting server: %v\n", err)
	}
}
