package main

import (
	"fmt"
	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger"
	_ "github.com/zen-flo/url-shortener/docs" // docs are generated by Swag CLI
	"github.com/zen-flo/url-shortener/internal/db"
	"github.com/zen-flo/url-shortener/internal/handler"
	"github.com/zen-flo/url-shortener/internal/middleware"
	"github.com/zen-flo/url-shortener/internal/service"
	"net/http"
	"time"
)

/*
Main function starts the HTTP server for the URL Shortener API.
*/

// @title URL Shortener API
// @version 1.0
// @description Simple REST API for shortening URLs.
// @host localhost:8080
// @BasePath /
func main() {
	// Create a new router
	r := chi.NewRouter()
	r.Use(middleware.MetricsMiddleware)
	// Separate route for /metrics
	r.Handle("/metrics", middleware.MetricsHandler())

	// Initialize database
	database := db.InitDB("urls.db")
	defer func() {
		if err := database.Close(); err != nil {
			fmt.Printf("Error closing database: %v\n", err)
		}
	}()

	// Initialize service and handler
	urlService := service.NewURLService(database)
	urlHandler := handler.NewURLHandler(urlService)

	// Register routes
	urlHandler.RegisterRoutes(r)

	// Start background metrics updater
	go func() {
		ticker := time.NewTicker(time.Minute)
		defer ticker.Stop()
		for range ticker.C {
			urlService.UpdateURLCount()
		}
	}()

	// Test route to check if the server is running
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		if _, err := w.Write([]byte("URL Shortener API is running")); err != nil {
			fmt.Printf("Error writing response: %v\n", err)
		}
	})

	// Health check endpoint
	r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("OK"))
	})

	// Swagger endpoint
	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8080/swagger/doc.json"), // URL до swagger.json
	))

	// Server port
	port := 8080
	fmt.Printf("Starting server on port %d...\n", port)

	// Start HTTP server
	if err := http.ListenAndServe(fmt.Sprintf(":%d", port), r); err != nil {
		fmt.Printf("Error starting server: %v\n", err)
	}
}
